# Generated by Django 5.1.1 on 2025-06-23 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FitbitAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fitbit_user_id",
                    models.CharField(
                        help_text="Fitbit에서 받은 고유 사용자 ID",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(help_text="Fitbit API 접근용 액세스 토큰"),
                ),
                (
                    "refresh_token",
                    models.TextField(help_text="액세스 토큰 갱신용 리프레시 토큰"),
                ),
                ("expires_at", models.DateTimeField(help_text="액세스 토큰 만료 시간")),
                ("scope", models.TextField(help_text="발급받은 권한 범위")),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer",
                        help_text="토큰 타입 (보통 Bearer)",
                        max_length=20,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Fitbit 프로필에서 가져온 이름",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        help_text="성별 (male/female/NA 등)", max_length=10, null=True
                    ),
                ),
                ("birthday", models.DateField(help_text="생년월일", null=True)),
                (
                    "height",
                    models.FloatField(
                        help_text="신장 (cm 또는 m 단위, Fitbit API 단위에 따라 조정)",
                        null=True,
                    ),
                ),
                ("weight", models.FloatField(help_text="몸무게 (kg)", null=True)),
                (
                    "last_synced",
                    models.DateTimeField(
                        help_text="마지막 데이터 동기화 시간", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="이 계정과 연결된 유저",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitbit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "핏빗 계정",
                "verbose_name_plural": "핏빗 계정",
            },
        ),
    ]
