# Generated by Django 5.1.1 on 2025-06-25 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitbit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitbitMinuteMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="데이터 기준 시각(UTC, 1 분 그리드 권장)"
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveSmallIntegerField(
                        help_text="심박수 (bpm)", null=True
                    ),
                ),
                (
                    "step_count",
                    models.PositiveIntegerField(
                        help_text="1분 동안의 걸음 수", null=True
                    ),
                ),
                (
                    "sleep_stage",
                    models.CharField(
                        choices=[
                            ("wake", "깸"),
                            ("light", "얕은잠"),
                            ("deep", "깊은잠"),
                            ("rem", "REM"),
                        ],
                        help_text="수면 단계(wake/light/deep/rem)",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("spo2", models.FloatField(help_text="혈중 산소포화도 (%)", null=True)),
                (
                    "respiratory_rate",
                    models.FloatField(
                        help_text="호흡수 (breaths per minute)", null=True
                    ),
                ),
                (
                    "skin_temperature",
                    models.FloatField(help_text="피부 온도 (°C)", null=True),
                ),
                ("weight_kg", models.FloatField(help_text="몸무게 (kg)", null=True)),
                ("height_cm", models.FloatField(help_text="키 (cm)", null=True)),
                (
                    "age_years",
                    models.PositiveSmallIntegerField(help_text="나이 (세)", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="연결된 Fitbit 계정",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minute_metrics",
                        to="fitbit.fitbitaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "분 단위 통합 메트릭",
                "verbose_name_plural": "분 단위 통합 메트릭",
                "indexes": [
                    models.Index(
                        fields=["account", "-timestamp"],
                        name="fitbit_fitb_account_f90b61_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "timestamp"),
                        name="unique_minute_per_account",
                    )
                ],
            },
        ),
    ]

    class Meta:
        app_label = 'my_jobs'