# Generated by Django 5.1.1 on 2025-08-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0002_fitbitminutemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitaccount',
            name='end_date',
            field=models.DateTimeField(db_column='end_date', help_text='연구 종료일', null=True),
        ),
        migrations.AddField(
            model_name='fitbitaccount',
            name='join_date',
            field=models.DateTimeField(db_column='join_date', help_text='연구 시작일', null=True),
        ),
        migrations.AddField(
            model_name='fitbitaccount',
            name='note',
            field=models.TextField(blank=True, db_column='note', db_comment='information of user', default='정보를 입력해주세요.', help_text='사용자에 대한 간략한 설명', null=True),
        ),
        migrations.AddField(
            model_name='fitbitaccount',
            name='pregnancy_start_date',
            field=models.DateTimeField(blank=True, db_column='pregnancy_start_date', db_comment='임신 시작일', help_text='임신 시작일을 입력해주세요', null=True),
        ),
        migrations.AddField(
            model_name='fitbitaccount',
            name='research_status',
            field=models.CharField(choices=[('preparing', '준비'), ('ongoing', '진행 중'), ('completed', '완료')], db_column='research_status', default='preparing', max_length=10),
        ),
        migrations.AddField(
            model_name='fitbitaccount',
            name='research_year',
            field=models.CharField(choices=[('none', '미확인'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], db_column='research_year', default='none', max_length=6),
        ),
    ]
