services:
  nginx:
    image: nginx:1.25.3
    networks:
      - network
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/data/static
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - 'apop'

  certbot:
    image: certbot/certbot
    dns:
      - 8.8.8.8
    volumes:
      - ./certbot:/data/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/data/static
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - network
    depends_on:
      - nginx
  apop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'apop'
    restart: always
    networks:
      - network
    volumes:
      - ./static:/djangoproject/static
    command: >
      bash -c "
      python3 manage.py makemigrations survey huami accounts &&
      python3 manage.py migrate &&
      gunicorn apop2.wsgi --workers 4 -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - 'db'
    environment:
      CSRF_TRUSTED_ORIGINS: "https://dai427.cbnu.ac.kr"
      AUTH_KEY: 'kong21'

  db:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    restart: always
    container_name: mariadb
    volumes:
      - mariadb-database:/var/lib/mysql
      - ./backups:/backups
    networks:
      - network
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: apopdb
      MARIADB_USER: example-user
      MARIADB_PASSWORD: example-password
      MARIADB_ROOT_PASSWORD: password
    command: >
      sh -c "
      service cron start &&
      mariadbd -u root"

networks:
  network:

volumes:
  mariadb-database:
  backups: