# Generated by Django 4.2.7 on 2024-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='mandatory',
            field=models.BooleanField(db_column='is_required', db_comment='필수 여부', default=False, help_text='이 질문이 응답해야 하는 필수 항목인지 여부'),
        ),
    ]
