# Generated by Django 4.2.7 on 2024-06-21 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(db_column='memo', db_comment='memo of status', help_text='상태 입력 내용입니다.', max_length=100)),
                ('date', models.DateField(db_column='date', db_comment='choose date', help_text='선택한 날짜입니다')),
                ('start_time', models.TimeField(db_column='start_time', db_comment='status start time', help_text='상태 변화 시작 시간입니다.')),
                ('end_time', models.TimeField(db_column='end_time', db_comment='status end time', help_text='상태 변화 끝난 시간입니다.')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='user id', help_text='유저 id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
