# Generated by Django 4.2.7 on 2024-06-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='note',
            field=models.TextField(blank=True, db_column='note', db_comment='비고', default='[비고]', help_text='건강상태에 대한 기록을 입력하세요.'),
        ),
    ]
