# Generated by Django 4.2.7 on 2024-06-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_status_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='note',
        ),
    ]
