# Generated by Django 4.2.7 on 2024-06-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_status_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='end_date',
            field=models.DateField(db_column='end_date', db_comment='choose end date', default='2024-01-01', help_text='상태 변화 끝난 날짜입니다'),
        ),
        migrations.AddField(
            model_name='status',
            name='note',
            field=models.TextField(blank=True, db_column='note', db_comment='비고', default='[비고]', help_text='건강상태에 대한 기록을 입력하세요.'),
        ),
        migrations.AddField(
            model_name='status',
            name='start_date',
            field=models.DateField(db_column='start_date', db_comment='choose start date', default='2024-01-01', help_text='상태 변화 시작한 날짜입니다'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateField(db_column='date', db_comment='choose date', help_text='상태 변화 끝난 날짜입니다'),
        ),
    ]
