# Generated by Django 4.2.7 on 2024-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_status_end_date_status_note_status_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='status',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='start_time',
        ),
        migrations.AddField(
            model_name='status',
            name='end_datetime',
            field=models.DateTimeField(db_column='end_datetime', db_comment='status end datetime', default='2024-06-27 00:00:00', help_text='상태 변화 끝난 시간과 날짜입니다.'),
        ),
        migrations.AddField(
            model_name='status',
            name='start_datetime',
            field=models.DateTimeField(db_column='start_datetime', db_comment='status start datetime', default='2024-06-27 00:00:00', help_text='상태 변화 시작한 시간과 날짜입니다.'),
        ),
    ]
