# Generated by Django 4.2.7 on 2024-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_status_date_remove_status_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='end_datetime',
            field=models.DateTimeField(db_column='end_datetime', db_comment='status end datetime', help_text='상태 변화 끝난 시간과 날짜입니다.'),
        ),
        migrations.AlterField(
            model_name='status',
            name='start_datetime',
            field=models.DateTimeField(db_column='start_datetime', db_comment='status start datetime', help_text='상태 변화 시작한 시간과 날짜입니다.'),
        ),
    ]
