# Generated by Django 4.2.7 on 2024-07-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_status_end_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
