# Generated by Django 5.1.1 on 2026-10-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userclicklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclicklog',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='세부정보'),
        ),
    ]
