# Generated by Django 4.2.7 on 2024-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huami', '0003_huamiaccount_end_date_huamiaccount_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huamiaccount',
            name='showed_sync_status',
            field=models.BooleanField(db_column='showed_sync_status', default=True, help_text='동기화 가능 여부'),
        ),
    ]
