# Generated by Django 4.2.7 on 2024-09-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huami', '0004_huamiaccount_showed_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='huamiaccount',
            name='age',
            field=models.IntegerField(db_column='age', help_text='사용자의 나이', null=True),
        ),
    ]
