# Generated by Django 4.2.7 on 2024-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huami', '0005_huamiaccount_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='huamiaccount',
            name='phone_number',
            field=models.CharField(db_column='phone_number', help_text='사용자 전화번호. 숫자만 저장', max_length=15, null=True),
        ),
    ]
