# Generated by Django 5.1.1 on 2024-12-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huami", "0006_huamiaccount_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="huamiaccount",
            name="pregnancy_start_date",
            field=models.DateTimeField(
                blank=True,
                db_column="pregnancy_start_date",
                db_comment="임신 시작일",
                help_text="임신 시작일을 입력해주세요",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="huamiaccount",
            name="phone_number",
            field=models.CharField(
                db_column="phone_number",
                help_text="전화번호를 입력해 주세요",
                max_length=15,
                null=True,
            ),
        ),
    ]
