# Generated by Django 5.1.1 on 2025-08-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huami', '0008_huamiaccount_research_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huamiaccount',
            name='research_year',
            field=models.CharField(choices=[('none', '미확인'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], db_column='research_year', default='none', max_length=6),
        ),
    ]
