# Generated by Django 5.1.1 on 2026-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huami', '0009_alter_huamiaccount_research_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='huamiaccount',
            name='pregnancy_day_at_join',
            field=models.PositiveSmallIntegerField(blank=True, db_column='pregnancy_day_at_join', db_comment='연구 시작일 기준 임신 주수(일)', help_text='연구 시작일 당시 임신 주수의 일수를 입력해주세요 (0~6)', null=True),
        ),
        migrations.AddField(
            model_name='huamiaccount',
            name='pregnancy_week_at_join',
            field=models.PositiveSmallIntegerField(blank=True, db_column='pregnancy_week_at_join', db_comment='연구 시작일 기준 임신 주수(주)', help_text='연구 시작일 당시 임신 주수를 입력해주세요', null=True),
        ),
    ]
