# Generated by Django 4.2.7 on 2024-06-20 05:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', db_comment='description of answer', help_text='질문 답변의 내용입니다.', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', db_comment='answer created time', help_text='질문 답변의 생성 시간입니다.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='answer updated time', help_text='질문 답변의 수정 시간입니다.')),
                ('value', models.IntegerField(blank=True, db_column='value', help_text='질문에 값이 존재할 경우 값을 기재합니다.', null=True)),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변',
                'db_table': 'answer',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', db_comment='question title', help_text='질문 제목', max_length=40)),
                ('description', models.TextField(db_column='description', db_comment='question description', help_text='질문 설명', max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', db_comment='question created time', help_text='질문 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='question updated time', help_text='질문 수정 시간')),
                ('type_filed', models.PositiveSmallIntegerField(choices=[(0, 'text'), (1, 'number'), (2, 'radio'), (3, 'select'), (4, 'multi_select'), (5, 'text_area')], db_column='type_filed', db_comment='question type', default=2, help_text='질문 타입')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문',
                'db_table': 'question',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', db_comment='survey title', help_text='설문지 제목', max_length=40)),
                ('description', models.TextField(db_column='description', db_comment='survey description', help_text='설문지 설명', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_comment='survey created time', help_text='설문지 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='survey updated time', help_text='설문지 수정 시간')),
            ],
            options={
                'verbose_name': '설문조사',
                'verbose_name_plural': '설문조사',
                'db_table': 'survey',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='create_at', db_comment='user survey created time', help_text='유저 설문 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', db_comment='user survey updated time', help_text='유저 설문 수정 시간')),
                ('survey', models.ForeignKey(db_column='survey_id', db_comment='survey id', help_text='설문 id', on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('user', models.ForeignKey(db_column='user_id', db_comment='user id', help_text='유저 id', on_delete=django.db.models.deletion.CASCADE, related_name='user_survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 설문',
                'verbose_name_plural': '유저 설문',
                'db_table': 'user_survey',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_column='order', db_comment='question order', help_text='질문 순서', validators=[django.core.validators.MinValueValidator(1)])),
                ('question', models.ForeignKey(db_comment='question', on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('survey', models.ForeignKey(db_comment='survey', on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'verbose_name': '설문조사 질문',
                'verbose_name_plural': '설문조사 질문',
                'db_table': 'survey_question',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(related_name='surveys', through='survey.SurveyQuestion', to='survey.question'),
        ),
        migrations.AddField(
            model_name='survey',
            name='users',
            field=models.ManyToManyField(related_name='surveys', through='survey.UserSurvey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, db_column='content', db_comment='reply to question', help_text='답변', max_length=255)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='survey.surveyquestion')),
                ('user_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='survey.usersurvey')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변',
                'db_table': 'reply',
                'ordering': ['user_survey'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_column='order', db_comment='answer order', help_text='답변 순서')),
                ('answer', models.ForeignKey(db_comment='answer', on_delete=django.db.models.deletion.CASCADE, to='survey.answer')),
                ('question', models.ForeignKey(db_comment='question', on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
            options={
                'verbose_name': '질문 답변',
                'verbose_name_plural': '질문 답변',
                'db_table': 'question_answer',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', through='survey.QuestionAnswer', to='survey.answer'),
        ),
    ]
