# Generated by Django 4.2.7 on 2024-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(db_column='is_required', db_comment='필수 여부', default=True, help_text='이 질문이 응답해야 하는 필수 항목인지 여부'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='is_required',
            field=models.BooleanField(db_column='is_required', db_comment='필수 여부', default=True, help_text='이 질문이 응답해야 하는 필수 항목인지 여부'),
        ),
    ]
