# Generated by Django 4.2.7 on 2024-07-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_is_required_surveyquestion_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='is_required',
        ),
    ]
