# Generated by Django 4.2.7 on 2024-07-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveyquestion_is_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='is_required',
            new_name='mandatory',
        ),
    ]
