# Generated by Django 4.2.7 on 2024-07-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_question_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
    ]
