# Generated by Django 4.2.7 on 2024-08-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_question_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(db_column='title', db_comment='question title', help_text='질문 제목', max_length=70),
        ),
    ]
