# Generated by Django 4.2.7 on 2024-08-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_other',
            field=models.BooleanField(db_column='is_other', db_comment='기타 옵션 여부', default=False, help_text='이 응답이 기타 옵션인지 여부'),
        ),
    ]
