# Generated by Django 5.1.1 on 2025-07-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_answer_is_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurvey',
            name='score',
            field=models.IntegerField(blank=True, db_column='score', help_text='설문 점수 총합', null=True),
        ),
    ]
