# Generated by Django 5.1.1 on 2025-12-30 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_usersurvey_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(help_text='행동 코드 (DRINK_WATER, BED_REST 등)', max_length=50)),
                ('performed', models.BooleanField(help_text='행동 수행 여부 (예/아니오)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='행동 기록 생성 시간')),
                ('user_survey', models.OneToOneField(db_comment='user survey id', on_delete=django.db.models.deletion.CASCADE, related_name='action_feedback', to='survey.usersurvey')),
            ],
            options={
                'verbose_name': '행동 수행 여부',
                'verbose_name_plural': '행동 수행 여부',
                'db_table': 'action_feedback',
            },
        ),
    ]
